import thinky from '../thinky';

const type = thinky.type;

const Article = thinky.createModel('Article', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    name       : String,
    state      : type.number().default(0),
    price      : type.number().default(0),
    capacity   : type.number().default(0),
    createdAt  : type.date().default(new Date()),
    editedAt   : type.date().default(new Date()),
    isRemoved  : type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Article.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Article.ensureIndex('createdAt');
Article.ensureIndex('editedAt');

Article.associate = models => {
    models.Article.belongsTo(models.User, 'user', 'User_id', 'id');
};

export default Article;