import thinky from '../thinky';

const type = thinky.type;

const Category = thinky.createModel('Category', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    name       : String,
    ghost      : type.boolean().default(false),
    createdAt  : type.date().default(new Date()),
    editedAt   : type.date().default(new Date()),
    isRemoved  : type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Category.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Category.ensureIndex('createdAt');
Category.ensureIndex('editedAt');

Category.associate = models => {
    models.Category.hasMany(models.Article, 'articles', 'id', 'User_id');
};

export default Category;