import thinky from '../thinky';

const type = thinky.type;

const Chat = thinky.createModel('Chat', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    message    : String,
    channel    : String,
    createdAt  : type.date().default(new Date()),
    editedAt   : type.date().default(new Date()),
    isRemoved  : type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Chat.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Chat.ensureIndex('createdAt');
Chat.ensureIndex('editedAt');

Chat.associate = models => {
    models.Chat.belongsTo(models.User, 'user', 'User_id', 'id');
};

export default Chat;