import thinky from '../thinky';

const type = thinky.type;

const Notification = thinky.createModel('Notification', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    priority   : type.number(),
    channel    : String,
    createdAt  : type.date().default(new Date()),
    editedAt   : type.date().default(new Date()),
    isRemoved  : type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

Notification.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Notification.ensureIndex('createdAt');
Notification.ensureIndex('editedAt');

Notification.associate = models => {
    models.Notification.hasOne(models.Type, 'type', 'id', 'User_id');
};

export default Notification;