import thinky from '../thinky';

const type = thinky.type;

const User = thinky.createModel('User', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    login      : String,
    password   : String,
    rank       : type.number().default(0),
    location   : String,
    createdAt  : type.date().default(new Date()),
    editedAt   : type.date().default(new Date()),
    isRemoved  : type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

User.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

User.ensureIndex('createdAt');
User.ensureIndex('editedAt');

User.associate = models => {
    models.User.hasMany(models.Article, 'articles', 'id', 'User_id');
};

export default User;